---
version: '3'
services:
  'service_0x12e8':
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: service_0x12e8
    env_file: .env
    ports:
      - '8000:8000'
    tty: true
    volumes:
      - ./0x21e8:/0x21e8
      - ./x21e8:/x21e8
    command: sh -c "uvicorn x21e8.main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 240 --reload"
  'planetmint':
    image: ghcr.io/planetmint/planetmint-aio:latest
    ports:
      - "9984:9984"
      - "9985:9985"
      - "26656:26656"
      - "26657:26657"
      - "26660:26660"
    command: 
      - /bin/bash
      - -c
      - |
        /etc/init.d/tarantool start
        tendermint init
        tendermint node --consensus.create_empty_blocks = false --rpc.laddr=tcp://0.0.0.0:26657&
        planetmint start
    healthcheck:
      test: ["CMD", "bash", "-c", "curl http://planetmint:9984 && curl http://planetmint:26657/abci_query"]
      interval: 3s
      timeout: 5s
      retries: 5
  'x21e8-readiness':
    image: busybox
    depends_on:
      cidresolver:
        condition: service_started
      planetmint:
        condition: service_healthy
  'redis':
    image: redis
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
  
  'cidresolver':
    image: ghcr.io/rddl-network/cid-resolver:latest
    depends_on:
      - redis
    ports:
      - '8080:8000'
    environment:
      - REDIS_HOST=redis
      - REDIS_AUTH=
      - JWT_SECRET=ZngzLUI1dFM5dXhTNEJTVnI1c2RQb1dsWm03YWtwMXo5UzRhSHBGWGhCZw==
      - JWT_DOMAIN=m2m.rddl.io
