
name: Deploy packages
on: 
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

permissions: 
  packages: write
  contents: write


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check -l 119"
          src: "."

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install dependencies
        run: poetry install --with dev

      - name: Install libwallycore
        run: |
          sudo apt update
          sudo apt install git
          git clone https://github.com/ElementsProject/libwally-core.git
          cd libwally-core/
          git checkout release_0.8.6
          git submodule init
          git submodule sync --recursive
          git submodule update --init --recursive
          sudo apt install autogen gcc g++ automake python3
          sudo apt install libtool swig
          sudo apt install python-is-python3
          sudo apt install python3-pip
          ./tools/autogen.sh 
          ./configure --enable-debug --enable-export-all --enable-swig-python
          make
          sudo make install
          cd ..

      - name: Run tests
        run: poetry run pytest -vvv tests


  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install dependencies
        run: poetry install --with dev 

      - name: Upload to PyPI
        run: |
          poetry build
          ppoetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
      
      - name: Upload to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

  publish-docker:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGE_DEPLOYMENT }}
      - name: Docker meta
        id: semver # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/rddl-network/0x21e8
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.semver.outputs.tags }}
          labels: ${{ steps.semver.outputs.labels }}
