# Copyright © 2020 Interplanetary Database Association e.V.,
# Planetmint and IPDB software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

name: Unit tests
on: [push, pull_request]

env: 
  LQD_RPC_PORT: 18886
  LQD_RPC_USER: user
  LQD_RPC_PASSWORD: password
  LQD_RPC_HOST: localhost
  PLNTMNT_ENDPOINT: http://node2-rddl-testnet.twilightparadox.com:9984
  WEB3STORAGE_TOKEN: ${{ secrets.WEB3STORAGE_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7

      - name: Install dependencies
        run: poetry install --with dev

      - name: Install libwallycore
        run: |
          sudo apt update
          sudo apt install git
          git clone https://github.com/ElementsProject/libwally-core.git
          cd libwally-core/
          git checkout release_0.8.6
          git submodule init
          git submodule sync --recursive
          git submodule update --init --recursive
          sudo apt install autogen gcc g++ automake python3
          sudo apt install libtool swig
          sudo apt install python-is-python3
          sudo apt install python3-pip
          ./tools/autogen.sh 
          ./configure --enable-debug --enable-export-all --enable-swig-python
          make
          sudo make install
          cd ..

      - name: Run tests
        run: poetry run pytest -vvv tests

      - name: Test build
        run: poetry build 


      
